builds:
  -
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    dockerfile: Dockerfile
    image_templates:
    - quay.io/hectorarranz/kubernetes-replicator-amd64:latest
    - quay.io/hectorarranz/kubernetes-replicator-amd64:{{ .Tag }}
    ids:
      - kubernetes-replicator
    goos: linux
    goarch: amd64
    goarm: ''
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
  -
    dockerfile: Dockerfile
    image_templates:
    - quay.io/hectorarranz/kubernetes-replicator-arm64:latest
    - quay.io/hectorarranz/kubernetes-replicator-arm64:{{ .Tag }}
    ids:
      - kubernetes-replicator
    goos: linux
    goarch: arm64
    goarm: ''
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
docker_manifests:
  - 
    name_template: quay.io/hectorarranz/kubernetes-replicator:latest
    image_templates:
    - quay.io/hectorarranz/kubernetes-replicator-amd64:{{ .Tag }}
    - quay.io/hectorarranz/kubernetes-replicator-arm64:{{ .Tag }}
  -
    name_template: quay.io/hectorarranz/kubernetes-replicator:{{ .Tag }}
    image_templates:
    - quay.io/hectorarranz/kubernetes-replicator-amd64:{{ .Tag }}
    - quay.io/hectorarranz/kubernetes-replicator-arm64:{{ .Tag }}
