name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and release image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker login -u "${{ secrets.QUAY_IO_USER }}" -p "${{ secrets.QUAY_IO_TOKEN }}" quay.io

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: "0.181.1"
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_USER_TOKEN }}